### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by CrimsonTautology** [bcserv/mapconfigs#3]
Hi, I was testing one of my plugins and after calling `sm_dump_handles` noticed that this plugin was leaving a lot of handles open.  This seems to be an issue with your `ExecuteMapSpecificConfigs` function;  specifically you create an array `adt_configs` but never call `CloseHandle` on it.

**Comment by berni2288** [comment]
Hey,

nice find. This one was one my first plugins I wrote in 2008 I think. Never thought I would ever introduce a handle leak.
Fixed with 3d4a69e45a72518ec304d958371303c4749a0161 :P
